### ISSUE TITLE
Kanban Board Set Up

### ISSUE THREAD

**Issue by adel-gu** [adel-gu/hotel-back-end#1]
- Kanban board link: https://github.com/users/adel-gu/projects/4/views/1
- Group Members: 04
    - Adel: @adel-gu 
    - Zuhaib: @Zuhaib042 
    - Joel: @Joel-100 
    - Aminue: @arabiu033 
- The board screenshot:
![image](https://user-images.githubusercontent.com/68030297/220961462-e37e84cd-9b51-4e0e-9c64-e3fba0a297b6.png)

**Comment by Meltrust** [comment]
Hi @adel-gu,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)



### To highlight

- All tasks are pointed fairly and have descriptions.✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by adel-gu** [comment]
Thank you @Meltrust 👏🏼👏🏼👏🏼.
